In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,54,36],np.int16)

In [3]:
arr1

array([ 1,  2, 54, 36], dtype=int16)

In [4]:
print(arr1)

[ 1  2 54 36]


In [5]:
print(arr1[3])

36


In [6]:
arr2=np.array([[1,2,4,7,8]],np.int16)

In [7]:
arr2

array([[1, 2, 4, 7, 8]], dtype=int16)

In [8]:
print(arr2[0,3])

7


# array creation

In [9]:
ar3=np.array([[1,2,3],[4,5,6],[3,7,5]],np.int16)

In [10]:
print(ar3)

[[1 2 3]
 [4 5 6]
 [3 7 5]]


In [11]:
ar3.dtype

dtype('int16')

In [12]:
ar3.shape

(3, 3)

In [13]:
ar3.size

9

In [14]:
zeros=np.zeros((3,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
range=np.arange(2,99)

In [17]:
range

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
       70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [18]:
lnspace=np.linspace(0,12,100)

In [19]:
print(lnspace)

[ 0.          0.12121212  0.24242424  0.36363636  0.48484848  0.60606061
  0.72727273  0.84848485  0.96969697  1.09090909  1.21212121  1.33333333
  1.45454545  1.57575758  1.6969697   1.81818182  1.93939394  2.06060606
  2.18181818  2.3030303   2.42424242  2.54545455  2.66666667  2.78787879
  2.90909091  3.03030303  3.15151515  3.27272727  3.39393939  3.51515152
  3.63636364  3.75757576  3.87878788  4.          4.12121212  4.24242424
  4.36363636  4.48484848  4.60606061  4.72727273  4.84848485  4.96969697
  5.09090909  5.21212121  5.33333333  5.45454545  5.57575758  5.6969697
  5.81818182  5.93939394  6.06060606  6.18181818  6.3030303   6.42424242
  6.54545455  6.66666667  6.78787879  6.90909091  7.03030303  7.15151515
  7.27272727  7.39393939  7.51515152  7.63636364  7.75757576  7.87878788
  8.          8.12121212  8.24242424  8.36363636  8.48484848  8.60606061
  8.72727273  8.84848485  8.96969697  9.09090909  9.21212121  9.33333333
  9.45454545  9.57575758  9.6969697   9.81818182  9.

In [20]:
random=np.empty((4,6))

In [21]:
random

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
random1=np.empty((3,5))

In [23]:
random1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
empty_like=np.empty_like(random)

In [25]:
empty_like

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
iden1=np.arange(64)

In [27]:
iden1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [28]:
iden1.reshape(8,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [29]:
iden1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [30]:
iden1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [31]:
iden1.shape

(64,)

In [32]:
iden1.size

64

In [33]:
matrix1=np.array(([1,4,3],[3,5,9],[3,9,6]))

In [34]:
matrix1

array([[1, 4, 3],
       [3, 5, 9],
       [3, 9, 6]])

In [35]:
matrix1.sum(axis=0)

array([ 7, 18, 18])

In [36]:
matrix1.sum(axis=1)

array([ 8, 17, 18])

In [37]:
matrix1.flat

In [38]:
for i in matrix1.flat:
    print(i)

1
4
3
3
5
9
3
9
6


In [39]:
matrix1.ndim

2

In [40]:
matrix1.nbytes

72

In [41]:
matrix1.argmax()

np.int64(5)

In [42]:
matrix1

array([[1, 4, 3],
       [3, 5, 9],
       [3, 9, 6]])

In [43]:
one=np.array([1,4,5,7,8,2,9,7,5])

In [44]:
print(one.argmax())

6


In [45]:
print(one.argsort())

[0 5 1 2 8 3 7 4 6]


In [46]:
matrix1.argmin()

np.int64(0)

In [47]:
matrix1.argsort()

array([[0, 2, 1],
       [0, 1, 2],
       [0, 2, 1]])

In [48]:
matrix1.argmax(axis=1)

array([1, 2, 1])

In [49]:
matrix1.argsort(axis=1)

array([[0, 2, 1],
       [0, 1, 2],
       [0, 2, 1]])

In [50]:
matrix1.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 2],
       [2, 2, 1]])

In [51]:
matrix2=np.array([[1, 7, 3],
       [3, 9, 3],
       [3, 9, 5]])

In [52]:
matrix1+matrix2

array([[ 2, 11,  6],
       [ 6, 14, 12],
       [ 6, 18, 11]])

In [53]:
matrix1*matrix2

array([[ 1, 28,  9],
       [ 9, 45, 27],
       [ 9, 81, 30]])

In [54]:
np.sqrt(matrix1)

array([[1.        , 2.        , 1.73205081],
       [1.73205081, 2.23606798, 3.        ],
       [1.73205081, 3.        , 2.44948974]])

In [55]:
matrix1.sum()

np.int64(43)

In [56]:
matrix1.max()

np.int64(9)

In [57]:
matrix1.min()

np.int64(1)

In [58]:
np.where(matrix1>5)

(array([1, 2, 2]), array([2, 1, 2]))

In [59]:
matrix1

array([[1, 4, 3],
       [3, 5, 9],
       [3, 9, 6]])

In [60]:
two=np.array([[6, 4, 3],
       [3, 4, 9],
       [3, 0, 3]])

In [61]:
np.where(two>4)

(array([0, 1]), array([0, 2]))

In [62]:
np.count_nonzero(two)

8

In [63]:
np.nonzero(two)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 2]))

In [64]:
import sys

In [65]:
py_ar=[1,6,8,66]

In [66]:
np_arr=np.array(py_ar)

In [67]:
sys.getsizeof(1)*len(py_ar)

112

In [68]:
np_arr.itemsize*np_arr.size

32

In [69]:
print(np_arr)

[ 1  6  8 66]
